### ISSUE TITLE
Why do the percentages for Report-only and Enforced don't sum up to those of Trusted Types?

### ISSUE THREAD

**Issue by ghost** [mikewest/mitigation-supply#5]
At the first graph of https://mitigation.supply/#trusted-types.

**Comment by mikewest** [comment]
The page-view percentages come from Chrome's telemetry, which encompasses an entire page: top-level and nested. The delta here likely reflects pages in which one document enforces and another document `report-only`s (and/or pages that serve both an enforced TT policy and a report-only TT policy).

**Comment by ghost** [comment]
Makes sense.

Then, at https://mitigation.supply/#trusted-types,

"The data below is gathered from [Chrome's usage statistics](https://chromestatus.com/metrics/feature/popularity), and represents the percentage of Chrome page loads that use Trusted Types in either enforcing or reporting mode, and of those, which enforce Trusted Types." should be rephrased. To e.g.

"The data below is gathered from [Chrome's usage statistics](https://chromestatus.com/metrics/feature/popularity), and represents the percentage of Chrome page loads that use Trusted Types in enforcing or reporting mode or both, only in enforcing mode and only in reporting mode."

**Comment by mikewest** [comment]
Sure. Patches welcome. :)
